version: '3.4'

services:
  service1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9001:80"

  service2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9002:80"
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
    expose:
     - 15672
     - 5672

